/**
 * VendorEnablement
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BrandIdentity { 
    id?: number;
    createdBy?: number;
    updatedBy?: number | null;
    createdDate?: string;
    udpatedDate?: string | null;
    brandName?: string | null;
    brandDescription?: string | null;
    brandLogofid?: string | null;
}

