/**
 * VendorEnablement
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ConsultantAddress {
  id?: number;
  createdBy?: number;
  updatedBy?: number | null;
  createdDate?: string;
  udpatedDate?: string | null;
  consultantId?: number;
  ownerType?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  pincode?: string | null;
  landmark?: string | null;
}
