/**
 * VendorEnablement
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Contact { 
    id?: number | null;
    createdBy?: number;
    updatedBy?: number | null;
    createdDate?: string;
    updatedDate?: string | null;
    consultantId?: number | null;
    resourceId?: number | null;
    phoneNo?: string | null;
}

