/**
 * VendorEnablement
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Master } from './master';
import { Address } from './address';
import { SubSkillMapping } from './subSkillMapping';
import { ProjectResourceMapping } from './projectResourceMapping';
import { VendorDetails } from './vendorDetails';
import { MainSkillMapping } from './mainSkillMapping';
import { Contact } from './contact';


export interface Resource { 
    id?: number | null;
    createdBy?: number;
    updatedBy?: number | null;
    createdDate?: string;
    updatedDate?: string | null;
    name: string;
    vendorDetailsId: number;
    vendorDetails?: VendorDetails;
    genderId: number;
    gender?: Master;
    age?: number;
    phoneNumber?: string | null;
    email?: string | null;
    jobTitle: string;
    contacts?: Array<Contact> | null;
    mainSkills?: Array<MainSkillMapping> | null;
    subSkills?: Array<SubSkillMapping> | null;
    addresses?: Array<Address> | null;
    projects?: Array<ProjectResourceMapping> | null;
}

