/**
 * VendorEnablement
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchResource } from './searchResource';


export interface SearchResourceGridRequest { 
    page?: number;
    pageSize?: number;
    sortColumn?: string | null;
    sortOrder?: string | null;
    uData?: SearchResource;
}

