/**
 * VendorEnablement
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { VendorDetails } from './vendorDetails';
import { Consultant } from './consultant';


export interface User { 
    id?: number;
    createdBy?: number;
    updatedBy?: number | null;
    createdDate?: string;
    udpatedDate?: string | null;
    email: string;
    password: string;
    roleId?: number;
    role?: Role;
    vendor?: VendorDetails;
    consultant?: Consultant;
}

