/**
 * VendorEnablement
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { SubSkillMapping } from './subSkillMapping';
import { MainSkillMapping } from './mainSkillMapping';
import { Contact } from './contact';


export interface Consultant { 
    id?: number | null;
    createdBy?: number;
    updatedBy?: number | null;
    createdDate?: string;
    updatedDate?: string | null;
    userId?: number;
    addresses?: Array<Address> | null;
    socialMediaAccounts?: string | null;
    alternateContact?: Array<Contact> | null;
    mainSkills?: Array<MainSkillMapping> | null;
    subSkills?: Array<SubSkillMapping> | null;
    isOpenForVerification?: boolean;
}

