/**
 * VendorEnablement
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Master } from './master';
import { Resource } from './resource';


export interface VendorDetails { 
    id?: number | null;
    createdBy?: number;
    updatedBy?: number | null;
    createdDate?: string;
    updatedDate?: string | null;
    userId?: number;
    resources?: Array<Resource> | null;
    emailId: string;
    vendorName: string;
    companyName: string;
    country: string;
    companyAddress: string;
    cinLlpIn: string;
    constitutionOfBusinessRid: number;
    constitutionOfBusiness?: Master;
    companyEstablished: string;
    companyIncorporationNumberAndCertificate: string;
    panCardFile: string;
    msmeNumber: string;
    gstinOrTaxId: string;
    sezEntityDetails: string;
    gstBillingAddress: string;
    gstFilingFrequencyRid: number;
    gstFilingFrequency?: Master;
    linkedinProfile: string;
    companyWebsite: string;
    teamSize: number;
    assistanceDetailsRid: number;
    assistanceDetails?: Master;
    relocationStates?: string | null;
    vendorContactNumber: string;
    alternativeContactPointName?: string | null;
    alternativeContactNumber?: string | null;
    alternativeContactEmail?: string | null;
    quarterlyRevenue?: number | null;
    openToBackgroundVerificationRid: number;
    openToBackgroundVerification?: Master;
    previousInvolvementWithUsRid: number;
    previousInvolvementWithUs?: Master;
}

